on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: mzacr123.azurecr.io
        username: ${{ secrets.acr_mzacr123_username }}
        password: ${{ secrets.acr_mzacr123_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t mzacr123.azurecr.io/mzaakscluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push mzacr123.azurecr.io/mzaakscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_mzaakscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep mzaaksdemo | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace mzaaksdemo`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: mzaaksdemo
        container-registry-url: mzacr123.azurecr.io
        container-registry-username: ${{ secrets.acr_mzacr123_username }}
        container-registry-password: ${{ secrets.acr_mzacr123_password }}
        secret-name: mzaaksclustedockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: mzaaksdemo
        manifests: |
          manifests/deployment-3.yml
          manifests/service-3.yml
        images: |
          mzacr123.azurecr.io/mzaakscluster:${{ github.sha }}
        imagepullsecrets: |
          mzaaksclustedockerauth
